### PR TITLE
Add more responses to dolike.py

### PR DESCRIPTION
**Pull request by sreyasaju**

### CODE REVIEW

**Comment by srevinsaju** [comment]
Please fix the style.

**Review by srevinsaju — APPROVED** [review]
Looks good, @TheDarkDrake any opinions?

**Comment by TheDarkDrake** [comment]
> Code looks good, @TheDarkDrake any opinions on the content?

Well, in the comedian reply, should it be mentioned as Mr Bean? Coz it's a show(sitcom). I guess it's better to mention it as "Rowan Atkinson", as he is the actor playing the role

**Comment by srevinsaju** [comment]
> > Code looks good, @TheDarkDrake any opinions on the content?
> 
> Well, in the comedian reply, should it be mentioned as Mr Bean? Coz it's a show(sitcom). I guess it's better to mention it as "Rowan Atkinson", as he is the actor playing the role

Yes, makes sense. you are right. cc @sreyasaju

**Comment by sreyasaju** [comment]
@TheDarkDrake @srevinsaju  Shall I proceed with the change in `about.py` too?

**Comment by TheDarkDrake** [comment]
I don't know if this is needed, but, the response to music feels like it's the response to "do you like CPU fan sound". Instead, can we keep it as, "I do like listening to the sound of rotating CPU fan and feel that it's like a harmonic music. So yeah, I love music!"
Just an opinion

**Review by TheDarkDrake — APPROVED** [review]

**Comment by sreyasaju** [comment]
> I don't know if this is needed, but, the response to music feels like it's the response to "do you like CPU fan sound". Instead, can we keep it as, "I do like listening to the sound of rotating CPU fan and feel that it's like a harmonic music. So yeah, I love music!"
> Just an opinion

```
elif "music" in self.normalized or ("song" in self.normalized):
       response = (
           "I listen to the rotating CPU fan. Its a harmonic music! "
           "At my server, we have tons of them."
       )
       emotion = Emotion.lol

elif "comedian" in self.normalized:
       response = "My favorite comedian is Mr Bean"
       emotion = Emotion.lol
```
@TheDarkDrake @srevinsaju,  This is the code which has been put up for the same by @srevinsaju  in `about.py`. Shall I change this too?

**Comment by TheDarkDrake** [comment]
> > I don't know if this is needed, but, the response to music feels like it's the response to "do you like CPU fan sound". Instead, can we keep it as, "I do like listening to the sound of rotating CPU fan and feel that it's like a harmonic music. So yeah, I love music!"
> > Just an opinion
> 
> ```
> elif "music" in self.normalized or ("song" in self.normalized):
>        response = (
>            "I listen to the rotating CPU fan. Its a harmonic music! "
>            "At my server, we have tons of them."
>        )
>        emotion = Emotion.lol
> 
> elif "comedian" in self.normalized:
>        response = "My favorite comedian is Mr Bean"
>        emotion = Emotion.lol
> ```
> 
> @TheDarkDrake @srevinsaju, This is the code which has been put up for the same by @srevinsaju in `about.py`. Shall I change this too?

If @srevinsaju  agrees, then yes ig

**Comment by srevinsaju** [comment]
> I don't know if this is needed, but, the response to music feels like it's the response to "do you like CPU fan sound". Instead, can we keep it as, "I do like listening to the sound of rotating CPU fan and feel that it's like a harmonic music. So yeah, I love music!"
> Just an opinion

I agree this should be the required change. You should use this line instead: `"I do like listening to the sound of rotating CPU fan and feel that it's like a harmonic music. So yeah, I love music!"`

**Comment by srevinsaju** [comment]
Also, I would say that, sugaroid need a favorite actor. This would require background research. Not watching movies is not an ideal reason.

**Comment by TheDarkDrake** [comment]
> Also, I would say that, sugaroid need a favorite actor. This would require background research. Not watching movies is not an ideal reason.

Indeed. Its better for sugaroid to have a clear answer to these kind of questions.

**Comment by sreyasaju** [comment]
> Also, I would say that, sugaroid need a favorite actor. This would require background research. Not watching movies is not an ideal reason.

Well, @srevinsaju and @TheDarkDrake  do you have any idea on what should be sugaroid's favorite actor?

**Review by srevinsaju — APPROVED** [review]

**Pull request merged**
