### PR TITLE
feat: define sugaroid's personality

### PR DESCRIPTION
**Pull request by srevinsaju**

### CODE REVIEW

**Review by TheDarkDrake — CHANGES_REQUESTED** [review]
Looks perfect, but an emotion emoji like "😁" would look better in the end

**Comment by srevinsaju** [comment]
Ok

**Comment by srevinsaju** [comment]
pushed again, does it look right now?

**Comment by TheDarkDrake** [comment]
> pushed again, does it look right now?

Yesh, looks great now

**Pull request merged**
